# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Arboresys'
name:             'Arboresys - testing stuff'
description:      'Hey, this is a test...'
# url:              http://arboresys.github.io
baseurl:          /

# Assets
images:           '/img'
pdfs:             '/pdf'


author:
  name:           'FS @ Arboresys'
  url:            'http://arboresys.github.io'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/arboresys/arboresys.github.io

gems:             [jekyll-paginate, jekyll-gist]


sass:
  style:          compressed
  sass_dir:       _sass
